server:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        worksChannel:
          binder: rabbit
          destination: work.exchange
          group: testgroup
  rabbitmq:
    password: "rabbitmq"
    username: "rabbitmq"
